### ISSUE TITLE
Can a table have foreign keys from two tables?

### ISSUE THREAD

**Issue by locphan2207** [locphan2207/Food-Stories#1]
In this website, users can comment on both recipe and story posts. In order to do it, I was wondering if `comments` table could have two foreign keys from two tables (`recipes` and `stories`)?    
Right now, I have to split `comments` into two different tables `recipe_comments` and `story_comments`

**Comment by anastassia-b** [comment]
This is a good question! It sounds like what you want to use are polymorphic associations. This would allow you to to call `recipes.comments` and `stories.comments` all with 1 comments table. This comments table will have a `commentable_id` column, as well as a `commentable_type`. 

Please refer to the docs:
* [http://guides.rubyonrails.org/association_basics.html#polymorphic-associations](http://guides.rubyonrails.org/association_basics.html#polymorphic-associations)
* [https://launchschool.com/blog/understanding-polymorphic-associations-in-rails](https://launchschool.com/blog/understanding-polymorphic-associations-in-rails)

**Comment by anastassia-b** [comment]
Great job implementing this with both comments and likes!
