### ISSUE TITLE
PA Review: Likes

### ISSUE THREAD

**Issue by locphan2207** [locphan2207/Food-Stories#10]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds
***
**Others:**

**Comment by anastassia-b** [comment]
Excellent! I can like recipes and stories, and also view them from my profile. The `liked-items-link` looks like a slightly different style than the rest of your style, but it's fine. 

- [ ] On the recipe page, the `detail-navbar-container` is well spaced out, but on the story view there is a space between `buttons` and `like-area`. Both are the same style. Maybe putting the 'like-area' inside the `buttons` would make them closer together.

This MVP is complete.

**Comment by locphan2207** [comment]
Done
