### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by locphan2207** [locphan2207/Food-Stories#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by locphan2207** [comment]
Finished styling. I don't know how to do the demo login yet

**Comment by anastassia-b** [comment]
Nice, this is really well done, the styling is really responsive. A few comments:

- [ ] Errors persist when I switch between forms. Please `clearErrors()` when the view changes.
- [ ] Guest image is breaking. You could download and store it in your assets.
- [ ] It would be nice if there was a way to access "Signup" within the Login form, and "Login" from the Signup form. As it is now, you have to click out of the modal and click the button again. 
- [ ] To add a demo account, you can make a "Demo" button which will `login(demoUser)` onClick, where `demoUser` is a guest user seeded in your database.

**Comment by anastassia-b** [comment]
Excellent work! Functionality is perfect and the styling is on point. This MVP is complete.
