### ISSUE TITLE
PA Review: Heroku

### ISSUE THREAD

**Issue by locphan2207** [locphan2207/Food-Stories#3]
- [x] First push on Heroku  
- [x] Final push on Heroku

**Comment by anastassia-b** [comment]
Please follow these guidelines to complete this MVP:
https://github.com/appacademy/curriculum/blob/master/full-stack-project/resources/helpful_tools/production-ready.md

**Comment by locphan2207** [comment]
Done

**Comment by anastassia-b** [comment]
Thanks, all your MVPs are complete! There isn't a PA Review: README, but I see that is complete as well. Awesome job!
