### ISSUE TITLE
PA Review: Recipes (Index and Show page)

### ISSUE THREAD

**Issue by locphan2207** [locphan2207/Food-Stories#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seedscipe Index page shows all recipes (Title, Total time and header image)
***
**Others:**
- [x] Small animation when hovering on Recipe Index Item
- [x] Canvas drawing for Cooking Time based on minute
- [x] Ingredient multiplying
- [x] Sticky Navbar switch when scrolling down
- [x] Section jumping by clicking on navigating buttons (Overview, Comments)
- [x] Suggestion Component

**Comment by anastassia-b** [comment]
Awesome work on this feature! I love the responsive ingredients list and the display of the baking times. The seed data is beautiful and the styling is impeccable. The recipe index page is complete, and you are finalizing the suggestion component on the recipe show page.

Based on our discussion today, here are some comments:
- [ ] You could optionally user [react-scroll](https://github.com/fisshy/react-scroll) to scroll to a precise location on the page and specify additional parameters. 
- [ ] Remove border-radius from the buttons to have a flat underline when active.
- [ ] A quick fix for the nav-bar bunching up when the window resizes is to give it a min-width.

**Comment by locphan2207** [comment]
In order to make the navigating buttons scroll to the correct positions, I created empty `<div>` and put them at correct positions. With those elements, I can use them as _"stop points"_ for the scrolling. 
By calling `.scrollIntoView()` on them, the navigating buttons can now bring users to correct positions.
