### ISSUE TITLE
PA Review: Recipe Search

### ISSUE THREAD

**Issue by locphan2207** [locphan2207/Food-Stories#7]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
***
**Others:**

**Comment by locphan2207** [comment]
The original site does live search, but I think if I do that, it will be communicating with the server backend a lot, which causes bad performance. So, I don't do live search. Users have to click search button to submit the search action.

**Comment by locphan2207** [comment]
Added

**Comment by locphan2207** [comment]
Did mean to close it. I don't know how to reopen it.

**Comment by anastassia-b** [comment]
Live recipe search works well! If you have time later to change the titles of recipes so there is a larger search space, that would be good. Now, all of them are roughly called "Testing recipe x with author x", so the results are more sparse. 

This MVP is complete.
