### ISSUE TITLE
PA Review: Stories (Index and Showpage)

### ISSUE THREAD

**Issue by locphan2207** [locphan2207/Food-Stories#8]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seedscipe Index page shows all recipes (Title, Total time and header image)
***
**Others:**
- [x] Small animation when hovering on Recipe Index Item
- [x] Sticky Navbar switch when scrolling down
- [x] Section jumping by clicking on navigating buttons (Overview, Comments)
- [x] Suggestion Component

**Comment by anastassia-b** [comment]
This is great work. The functionality and styling is complete. One note:
- [ ] The "See All" link from the homepage jumps to the middle of the page it is linking to instead of the top. Please fix this for both recipes and stories.

Other than that, this MVP is complete!
